<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.34.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageReference Include="Grpc.Tools" Version="2.78.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\odometer.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\battery.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\exterior.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\availability.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\parkingclimatization.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\chronos.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\parkingclimatetimer.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
